config/routes.rb
Rails.application.routes.draw do
  
  resources :admins  
  resources :students
  resources :teachers
  resources :assigments
  
  root 'pages#home' 
  get '/student', to: 'students#home', as: 'student_dashboard'
  get '/teacher', to: 'teachers#home', as: 'teacher_dashboard'
  get '/admin', to: 'admins#home', as: 'admin_dashboard'

  get '/login', to: 'pages#login'
  post '/login', to: 'pages#login_session' # Ruta para el inicio de sesión (POST)
  delete '/logout', to: 'pages#destroy'

  get '/admin/students', to: 'admins#students'
  get '/admin/students/:id/edit', to: 'admins#edit_student', as: 'edit_admin_student'
  post '/admin/create_student', to: 'admins#create_student'
  delete '/admin/students/:id', to: 'admins#delete_student', as: 'delete_admin_student'
  patch '/admin/students/:id', to: 'admins#update_student', as: 'update_admin_student'

  get '/admin/teachers', to: 'admins#teachers'
  get '/admin/teachers/:id/edit', to: 'admins#edit_teacher', as: 'edit_admin_teacher'
  post '/admin/create_teacher', to: 'admins#create_teacher'
  delete '/admin/teachers/:id', to: 'admins#delete_teacher', as: 'delete_admin_teacher'
  patch '/admin/teachers/:id', to: 'admins#update_teacher', as: 'update_admin_teacher'

  get '/admin/assignments', to: 'admins#assignments'
  get '/admin/assignments/:id/edit', to: 'admins#edit_assignment', as: 'edit_admin_assignment'
  post '/admin/create_assignment', to: 'admins#create_assignment'
  delete '/admin/assignments/:id', to: 'admins#delete_assignment', as: 'delete_admin_assignment'
  patch '/admin/assignments/:id', to: 'admins#update_assignment', as: 'update_admin_assignment'

  get '/admin/assignments_teachers', to: 'admins#assignments_teachers'
  get '/admin/assignments_teachers/:id/edit', to: 'admins#edit_assignment_teacher', as: 'edit_admin_assignment_teacher'
  post '/admin/create_assignment_teacher', to: 'admins#create_assignment_teacher'
  delete '/admin/assignments_teachers/:id', to: 'admins#delete_assignment_teacher', as: 'delete_admin_assignment_teacher'
  patch '/admin/assignments_teachers/:id', to: 'admins#update_assignment_teacher', as: 'update_admin_assignment_teacher'
end

app/views/admins/_alert.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible fade show fixed-notification" role="alert">
    <i class="fa-solid fa-check-circle me-2"></i> <%= flash[:success] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show fixed-notification" role="alert">
    <i class="fa-solid fa-triangle-exclamation me-2"></i> <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning alert-dismissible fade show fixed-notification" role="alert">
    <i class="fa-solid fa-triangle-exclamation me-2"></i> <%= flash[:warning] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/admins/assignments.html.erb
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Administrator</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<% if current_user.is_a?(Admin) %>

    <main class="d-flex flex-nowrap">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary position-fixed vh-100" style="width: 280px;">
            <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <img src="https://img.freepik.com/vector-gratis/diseno-icono-degradado-logotipo-empresa-moderna_53876-120504.jpg?w=826&t=st=1693366444~exp=1693367044~hmac=8dd716f6cb7664515a66c4f2707df8c484eaa72ae861ea2283305a6fb211f7ae" alt="" width="32" height="32" class="rounded-circle me-2">
                <span class="fs-4">Hi, <%= current_user.name %></span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li>
                    <a href="<%= '/admin' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-house me-2"></i>Home
                    </a>
                </li>
                <li>
                    <a href="<%= '/admin/students' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-graduation-cap me-2"></i>Students
                    </a>
                </li>
                <li>
                    <a href="<%= '/admin/teachers' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-chalkboard-user me-2"></i>Teachers
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<%= '/admin/assignments' %>" class="nav-link active" aria-current="page">
                        <i class="fa-solid fa-book-open me-2"></i>Assignments
                    </a>
                </li>
                <li><hr></li>
                <li>
                    <a href="<%= '/admin/assignments_teachers' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-thumbtack"></i>Make a class
                    </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                    <strong>User</strong>
                </a>
                <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to 'Sign out', logout_path, method: :delete, class: "dropdown-item" %></li>
                </ul>
            </div>
        </div>  
    </main>

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Manage <b>Assignments</b></h2>
                        </div>
                    <div class="col-sm-6">
                        <div class="d-flex justify-content-end">
                            <div class="search-box">
                                <i class="fa-solid fa-magnifying-glass"></i>
                                <input type="text" class="form-control" placeholder="Search&hellip;">
                            </div>
                            <button id="addStudentBtn" class="btn btn-success" data-toggle="modal" data-target="#addStudentModal" style="width: 100px;"><i class="fa-solid fa-plus"></i> <span>Add</span></button> 
                        </div>
                    </div>

                </div>
            </div>
            <div class="table-responsive custom-table-size">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <% @assignments.each do |assignment| %>
                        <tr> 
                            <td style="text-align: center;"> <%= assignment.id %>          </td>
                            <td style="text-align: center;"> <%= assignment.name %>        </td>
                            <td class="actions-column">                               
                                <%= link_to edit_admin_assignment_path(assignment), class: 'edit' do %>
                                    <i class="fa-solid fa-pen"></i>
                                <% end %>
                                <%= link_to delete_admin_assignment_path(assignment), method: :delete, data: { confirm: 'Delete this assignment?' }, class: 'delete' do %>
                                    <i class="fa-solid fa-trash"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            </div>
            <div class="clearfix">
                <div class="hint-text">Showing <b>1</b> out of <b>?</b> entries</div>
                <%= will_paginate @assignments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>

            </div>
        </div>        
    </div>

  <!-- add Modal HTML -->
  <%= form_for :assignment, url: '/admin/create_assignment' do |f| %>
    <div id="addStudentModal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">											
                    <h4 class="modal-title">Add Assignment</h4>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true"></button>
                </div>
                <div class="modal-body">					
                    <div class="form-group">
                        <%= f.label :Name%>
                        <%= f.text_field :name, class: "form-control", required: true, pattern: "[a-zA-Zá-úÁ-Ú\s]*", title: "Enter a valid assignature"  %>
                    </div>              
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <%= f.submit "Add", class: "btn btn-success"%>
                </div>
            </div>
        </div>
    </div>
  <% end %>
  <%= render 'alert' %>  
<% else %>
<p>No has iniciado sesión como admin.</p>
<% end %>

</body>
</html>

app/views/admins/assignments_teachers.html.erb
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Administrator</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body> 
<% if current_user.is_a?(Admin) %>

  <main class="d-flex flex-nowrap">
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary position-fixed vh-100" style="width: 280px;">
      <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="https://img.freepik.com/vector-gratis/diseno-icono-degradado-logotipo-empresa-moderna_53876-120504.jpg?w=826&t=st=1693366444~exp=1693367044~hmac=8dd716f6cb7664515a66c4f2707df8c484eaa72ae861ea2283305a6fb211f7ae" alt="" width="32" height="32" class="rounded-circle me-2">
        <span class="fs-4">Hi, <%= current_user.name %></span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="<%= '/admin' %>" class="nav-link link-body-emphasis" aria-current="page">
              <i class="fa-solid fa-house me-2"></i>Home
          </a>
        </li>
        <li>
          <a href="<%= '/admin/students' %>" class="nav-link link-body-emphasis">
              <i class="fa-solid fa-graduation-cap me-2"></i>Students
          </a>
        </li>
        <li>
          <a href="<%= '/admin/teachers' %>" class="nav-link link-body-emphasis">
              <i class="fa-solid fa-chalkboard-user me-2"></i>Teachers
          </a>
        </li>
        <li>
          <a href="<%= '/admin/assignments' %>" class="nav-link link-body-emphasis">
              <i class="fa-solid fa-book-open me-2"></i>Assignments
          </a>
        </li>
        <li><hr></li>
        <li>
          <a href="<%= '/admin/assignment_teacher' %>" class="nav-link active">
              <i class="fa-solid fa-thumbtack"></i>Make a class
          </a>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
          <strong>User</strong>
        </a>
        <ul class="dropdown-menu text-small shadow">
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to 'Sign out', logout_path, method: :delete, class: "dropdown-item" %></li>
        </ul>
      </div>
    </div>  
  </main>

  <div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Manage <b>Class</b></h2>
                    </div>
                <div class="col-sm-6">
                    <div class="d-flex justify-content-end">
                        <div class="search-box">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <input type="text" class="form-control" placeholder="Search&hellip;">
                        </div>
                        <button id="addClassBtn" class="btn btn-success" data-toggle="modal" data-target="#addClassModal" style="width: 100px;"><i class="fa-solid fa-plus"></i> <span>Add</span></button> 
                    </div>
                </div>

            </div>
        </div>
        <div class="table-responsive custom-table-size">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Assignment</th>
                    <th>Name Teacher</th>
                    <th>Grade</th>
                    <th>Group</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
              <% @assignments_teachers.each do |at| %>               
                <tr>
                  <td style="text-align: center;"><%= at.id %>              </td>
                  <td style="text-align: center;">
                    <% if at.assignment.present? %>
                      <%= at.assignment.name %>
                    <% else %>
                    Pending to assign an assignment
                    <% end %>
                  </td>
                  <td style="text-align: center;">
                    <% if at.teacher.present? %>
                      <%= "#{at.teacher.name} #{at.teacher.last_name}" %>
                    <% else %>
                      Pending to assign a teacher
                    <% end %>
                  </td>
                  <td style="text-align: center;"><%= at.grade %>           </td>
                  <td style="text-align: center;"><%= at.group %>           </td>
                  <td class="actions-column" style="text-align: center;">                               
                    <%= link_to edit_admin_assignment_teacher_path(at), class: 'edit' do %>
                      <i class="fa-solid fa-pen"></i>
                    <% end %>
                    <%= link_to delete_admin_assignment_teacher_path(at), method: :delete, data: { confirm: 'Delete this class?' }, class: 'delete' do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
        </div>
        <div class="clearfix">
            <div class="hint-text">Showing <b>1</b> out of <b>?</b> entries</div>
            <%= will_paginate @assignments_teachers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>            
        </div>

        </div>
    </div>        
</div>

<%= form_for :assignment_teacher, url: '/admin/create_assignment_teacher' do |f| %>
    <div id="addClassModal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">											
                    <h4 class="modal-title">Add Class</h4>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true"></button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <%= f.label :'Name Assignment'%>
                        <% if Assignment.count.zero? %>
                          <p class="form-select text-danger">There are no assignments available in the database. Please add assignments before continuing.</p>
                        <% else %>
                          <%= f.collection_select(:assignment_id, Assignment.all, :id, :name, { selected: Assignment.first.id }, { class: 'form-select', required: true }) %>
                        <% end %>
                    </div> 					
                    <div class="form-group">
                        <%= f.label :'Name Teacher'%>
                        <% if Teacher.count.zero? %>
                          <p class="form-select text-danger">There are no teachers available in the database. Please add teachers before continuing.</p>
                        <% else %>
                          <%= f.collection_select(:teacher_id, Teacher.all, :id, lambda { |teacher| "#{teacher.name} #{teacher.last_name}" }, { selected: Teacher.first.id }, { class: 'form-select', required: true }) %>
                        <% end %>
                    </div> 
                    <div class="form-group">
                        <%= f.label :Grade %>
                        <%= f.select :grade, [1,2,3,4,5,6], { selected: 1 }, class: "form-select", required: true %>                                        
                    </div>
                    <div class="form-group">
                        <%= f.label :Groups %>
                        <div class="form-check form-check-inline" style="position: relative; float: right;">
                          <label class="form-check-label" style="position: absolute; top: 50%; transform: translateY(-50%);">All</label>
                          <input class="form-check-input" type="checkbox" id="select-all-checkbox" style="width: 20px; height: 20px; margin-right: 5px;">
                        </div>
                        <br>
                        <% ('A'..'F').to_a.each do |group| %>
                          <div class="form-check form-check-inline" style="position: relative;">
                            <%= check_box_tag 'assignment_teacher[group][]', group, false, class: 'form-check-input', style: "width: 20px; height: 20px; margin-right: 5px;" %>
                            <%= label_tag "assignment_teacher_group_#{group}", group, class: 'form-check-label', style: "position: absolute; top: 50%; transform: translateY(-50%);" %>
                          </div>
                        <% end %>
                    </div>                 
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <%= f.submit "Add", class: "btn btn-success"%>
                </div>
            </div>
        </div>
    </div>
  <% end %>
  
  
 
  <%= render 'alert' %>  

<% else %>
  <p>No has iniciado sesión como admin.</p>
<% end %>
  
  
</body>
</html>

app/views/admins/students.html.erb
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Administrator</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
<% if current_user.is_a?(Admin) %>

    <main class="d-flex flex-nowrap">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary position-fixed vh-100" style="width: 280px;">
            <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <img src="https://img.freepik.com/vector-gratis/diseno-icono-degradado-logotipo-empresa-moderna_53876-120504.jpg?w=826&t=st=1693366444~exp=1693367044~hmac=8dd716f6cb7664515a66c4f2707df8c484eaa72ae861ea2283305a6fb211f7ae" alt="" width="32" height="32" class="rounded-circle me-2">
                <span class="fs-4">Hi, <%= current_user.name %></span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li>
                    <a href="<%= '/admin' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-house me-2"></i>Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<%= '/admin/students' %>" class="nav-link active" aria-current="page">
                        <i class="fa-solid fa-graduation-cap me-2"></i>Students
                    </a>
                </li>
                <li>
                    <a href="<%= '/admin/teachers' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-chalkboard-user me-2"></i>Teachers
                    </a>
                </li>
                <li>
                    <a href="<%= '/admin/assignments' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-book-open me-2"></i>Assignments
                    </a>
                </li>
                <li><hr></li>
                <li>
                    <a href="<%= '/admin/assignments_teachers' %>" class="nav-link link-body-emphasis">
                        <i class="fa-solid fa-thumbtack"></i>Make a class
                    </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                    <strong>User</strong>
                </a>
                <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to 'Sign out', logout_path, method: :delete, class: "dropdown-item" %></li>
                </ul>
            </div>
        </div>  
    </main>
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Manage <b>Students</b></h2>
                        </div>
                    <div class="col-sm-6">
                        <div class="d-flex justify-content-end">
                            <div class="search-box">
                                <i class="fa-solid fa-magnifying-glass"></i>
                                <input type="text" class="form-control" placeholder="Search&hellip;">
                            </div>
                            <button id="addStudentBtn" class="btn btn-success" data-toggle="modal" data-target="#addStudentModal" style="width: 100px;"><i class="fa-solid fa-plus"></i> <span>Add</span></button> 
                        </div>
                    </div>

                </div>
            </div>
            <div class="table-responsive custom-table-size">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Account</th>
                        <th>Grade</th>
                        <th>Group</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <% @students.each do |student| %>
                        <tr> 
                            <td style="text-align: center;"> <%= student.id %>          </td>
                            <td> <%= student.name %>                                    </td>
                            <td> <%= student.last_name %>                               </td>
                            <td style="text-align: center;"> <%= student.email %>       </td>
                            <td style="text-align: center;"> <%= student.account %>     </td>
                            <td style="text-align: center;"> <%= student.grade %>       </td>
                            <td style="text-align: center;"> <%= student.group %>       </td>
                            <td class="actions-column">                               
                                <%= link_to edit_admin_student_path(student), class: 'edit' do %>
                                    <i class="fa-solid fa-pen"></i>
                                <% end %>
                                <%= link_to delete_admin_student_path(student), method: :delete, data: { confirm: 'Delete this student?' }, class: 'delete' do %>
                                    <i class="fa-solid fa-trash"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            </div>
            <div class="clearfix">
                <div class="hint-text">Showing <b>1</b> out of <b>?</b> entries</div>
                <%= will_paginate @students, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>

            </div>
        </div>        
    </div>
  
  <!-- add Modal HTML -->
  <%= form_for :student, url: '/admin/create_student' do |f| %>
    <div id="addStudentModal" class="modal fade">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">						
                    <h4 class="modal-title">Add Student</h4>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true"></button>
                </div>
                <div class="modal-body">	
                  <div class="form-group">
                      <%= f.label :Photo%>
                      <%= f.file_field :avatar, class: "form-control", required: true %>
                  </div>
                  <div class="form-group">
                      <%= f.label :Name%>
                      <%= f.text_field :name, class: "form-control", required: true, pattern: "[a-zA-Zá-úÁ-Ú\s]*", title: "Enter a valid name"  %>
                  </div>
                  <div class="form-group">
                      <%= f.label :'Last Name'%>
                      <%= f.text_field :last_name, class: "form-control", required: true, pattern: "[a-zA-Zá-úÁ-Ú\s]*", title: "Enter a valid last name" %>
                  </div>
                  <div class="form-group">
                      <%= f.label :Email%>
                      <%= f.email_field :email, class: "form-control", required: true %>
                  </div>
                  <div class="form-group">
                    <%= f.label :Password%>
                    <%= f.password_field :password, class: "form-control", value: @password, readonly: true %>
                </div>
                  <div class="form-group">
                      <%= f.label :'Number Account'%>
                      <%= f.number_field :account, class: "form-control", value: @account, readonly: true %>
                      
                  </div>
                  <div class="row g-3">
                    <div class="col-md-6">
                        <%= f.label :Grade%>
                        <%= f.select :grade, [1,2,3,4,5,6], { selected: 1 }, class: "form-select", required: true %>                                        
                    </div>
                    <div class="col-md-6">
                        <%= f.label :Group%>
                        <%= f.select :group, ["A", "B", "C", "D", "E", "F"], { selected: "A" }, class: "form-select", required: true %>                                        
                    </div>    
                  </div>								
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <%= f.submit "Add", class: "btn btn-success"%>
                </div>
            </div>
        </div>
    </div>
  <% end %>
  <%= render 'alert' %>  
  <% else %>
  <p>No has iniciado sesión como admin.</p>
<% end %>
</body>
</html>